# TetherElement configuration file to define parameters

# TetherElement parameters
TetherElement:
    mass: 10
    length: 1
    volume: 0.001

# Length coefficients for links
Length:
    Kp: 15.
    Kd: 2.
    Ki: 2.

# Torque coefficients for rigidity
Torque:
    Kp: 10.
    Kd: 1.
    Ki: 0.

Drag:
    f: 1.0