# TetherElement configuration file to define parameters

# TetherElement parameters
TetherElement:
    mass: 10
    length: 2.5
    volume: 0.001

# Length coefficients for links
Length:
    Kp: 350.
    Kd: 5.0
    Ki: 35.0

# Torque coefficients for rigidity
Torque:
    Kp: 0.
    Kd: 0.
    Ki: 0.

Drag:
    f: 15.