# TetherElement configuration file to define parameters

# TetherElement parameters
TetherElement:
    mass: 10
    length: 1
    volume: 0.001

# Length coefficients for links
Length:
    Kp: 1.
    Kd: 0
    Ki: 0

# Torque coefficients for rigidity
Torque:
    Kp: 0.
    Kd: 0
    Ki: 0

Drag:
    f: 1.0