# TetherElement configuration file to define parameters

# TetherElement parameters
TetherElement:
    mass: 8.93
    length: 1.78
    volume: 0.00014

# Length coefficients for links
Length:
    Kp: 200
    Kd: 3.5
    Ki: 3

# Torque coefficients for rigidity
Torque:
    Kp: 50
    Kd: 1.0
    Ki: 1.0

Drag:
    f: 1.0