# TetherElement configuration file

# Length coefficients for links
Length:
    Kp: 80.0
    Kd: 6.
    Ki: 6.

# Torque coefficients for twist
Twist:
    Kp: 50.
    Kd: 100.
    Ki: 0.

# Torque coefficients for bend
Bend:
    Kp: 0.
    Kd: 0.
    Ki: 0.

Drag:
    f: 30.