# TetherElement configuration file

# Length coefficients for links
Length:
    Kp: 200.0
    Kd: 6.0
    Ki: 100.0

# Torque coefficients for rigidity
Torque:
    Kp: 0.
    Kd: 0.
    Ki: 0.

Drag:
    f: 15.