# TetherElement configuration file

# Length coefficients for links
Length:
    Kp: 150.0
    Kd: 4.0
    Ki: 14.0

# Torque coefficients for twist
Twist:
    Kp: 50.
    Kd: 100.
    Ki: 0.

# Torque coefficients for bend
Bend:
    Kp: 0.
    Kd: 0.
    Ki: 0.

Drag:
    f: 30.