# Tether configuration file

# Tether parameters
Tether:
    length: 25
    n: 11
    linear_mass: 5
    linear_volume: 0.0005

# Environment parameters
Environment:
    rho: 1000
    g: 9.81

Elements:
    position_head:
        x: 11.0
        y: 0.0
        z: 2.0
        angle: 1.0
    position_tail:
        x: 18.0
        y: 3.0
        z: -2.0
        angle: 0.0